#!/usr/bin/python

# This file is part of KEmuFuzzer.
# 
# KEmuFuzzer is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation, either version 3 of the License, or (at your option) any later
# version.
# 
# KEmuFuzzer is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
# A PARTICULAR PURPOSE.  See the GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License along with
# KEmuFuzzer.  If not, see <http://www.gnu.org/licenses/>.


import sys
from tc import TestCase

def main(f):
    tc = TestCase.load(f)
    print tc

if __name__ == "__main__":
    n = False
    for f in sys.argv[1:]:
        if n:
            print
        if len(sys.argv) > 2:
            print f
        main(f)
        n = True
